[package]
name = "rewrite_unwraps"
version = "0.1.0"
authors = ["Austin Bonander <austin.bonander@gmail.com>"]

[lib]
crate-type = ["proc-macro"]

[dependencies]
syn = { version = "*", features = ["full", "parsing", "printing", "fold"] }
quote = "*"
